#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void resetEncoder();
void hitWall(int dist);
void followLine();
void turn(int degrees);
void moves(int speed,int time);
void cease();
void turnLeft(int speed);
void turnRight(int speed);


task main()
{
	//Step 1//
	hitWall(1000);

	//Step 2//
	moves(-10,500);
	turn(90);
	moves(100,500);
	followLine();

	//Step 3//
	turn(30);
	hitWall(1000);
	moves(-10,1000);
	turn(-90);
	hitWall(1000);
	moves(-10,1000);
	//angle uturn right
	turn(-180);

	//Step 5//
	hitWall(1000);
}


void resetEncoder()
{
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
}

void hitWall(int dist){
	resetEncoder();
	moves(100,-1);
	while (getMotorEncoder(motorB) < dist)
	{
		if (getTouchValue(touchSensor)==1)
		{
			break;
		}
	}
	cease();
}
void followLine(){
bool lineFound;
	while (true)
	{
		if (getColorName(colorSensor) == colorRed)
		{ lineFound = true; }

		else if (getColorName(colorSensor) != colorRed)
		{//find the line
			lineFound = false;
			cease();
			//search left
			resetGyro(gyroSensor);
			while (getGyroDegrees(gyroSensor) < 120 && lineFound == false)
			{
				turnLeft(50);
				if (getColorName(colorSensor) == colorRed)
				{
					lineFound = true;
					break;
				}
			}//end while
			cease();

			//if still not found, return to position
			if (lineFound == false)
			{
				resetGyro(gyroSensor);
				while (getGyroDegrees(gyroSensor) > -120 && lineFound == false)
				{
					turnLeft(-50);
					if (getColorName(colorSensor) == colorRed)
					{ lineFound = true; }
				}//end while
				cease();
			}

			//search right
			resetGyro(gyroSensor);
			while (getGyroDegrees(gyroSensor) > -120 && lineFound == false)
			{
				turnRight(50);
				if (getColorName(colorSensor) == colorRed)
				{ lineFound = true; }
			}//end while
			cease();

			//if still not found, return to position
			if (lineFound == false)
			{
				resetGyro(gyroSensor);
				while (getGyroDegrees(gyroSensor) < 120 && lineFound == false)
				{
					turnRight(-50);
					if (getColorName(colorSensor) == colorRed)
					{ lineFound = true; }
				}//end while
				cease();
			}

		}//big if clause end

		if (lineFound == true)
		{
			moves(50,-1);
		}
		if (lineFound == false)
		{
			cease();
			break;
		}
	}
}
void turn (int degrees){
	resetGyro(gyroSensor);

	if(degrees > 0 ){
		while(getGyroDegrees(gyroSensor) < degrees)
		{
			turnLeft(50);
		}
		}else{
		while(getGyroDegrees(gyroSensor) > degrees)
		{
			turnRight(50);
		}
		cease();
	}
}
void moves(int speed,int time)
{
	setMotorSpeed(motorB, speed);
	setMotorSpeed(motorC, speed);
	if(time == -1){
		delay(time);
	}
}
void cease()
{
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
}

void turnLeft(int speed)
{
	setMotorSpeed(motorB, speed);
	setMotorSpeed(motorC, 0);
}


void turnRight(int speed)
{
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 50);
}
