#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
//#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void startResets();
void rotateBase(int motorTarget);
void liftArm(int motorTarget);
void moveClamp(int motorTarget);
void doSweepSearch();
void retrieveAndPlaceObject();

int baseMotorSpeed = 50;
int armMotorSpeed = 50;
int clampMotorSpeed = 30;
TLegoColors target_colour = colorRed;
int objectSeen = 0;
//boolean baseRotatedLeft = false; //helps keep track of which way the arm has moved
//boolean baseRotatedRight = false;

//sets all encoders at start to 0 for all motors, to accurately measure angles
void startResets(){
    resetMotorEncoder(baseMotor);
    resetMotorEncoder(armMotor);
    resetMotorEncoder(clampMotor);
}

//rotate +180/-180 from start based on setMotorTarget (or until colour sensor sees a red object)
//if motorTarget +ve, rotate right, if -ve, rotate left, if 0, return to start position
//speed must always be positive, since motorTarget determines left/right movt
void rotateBase(int motorTarget){
//    if (motorTarget > 0){ //rotated clockwise (keeping track)
//        baseRotatedRight = true;
//        baseRotatedLeft = false;
//    }
//    else if (motorTarget < 0){ //rotating anticlockise (keeping track)
//        baseRotatedLeft = true;
//        baseRotatedRight = false;
//    }
//    else if (motorTarget == 0){ //back to start position
//        resetMotorEncoder(baseMotor);
//        baseRotatedRight = false;
//        baseRotatedLeft = false;
//    }
    if (motorTarget == 0){
        resetMotorEncoder(baseMotor);
    }

    while (getColorName(colorSensor) != target_colour) {
        setMotorTarget(baseMotor, motorTarget, baseMotorSpeed); //rotate to desired angle
        wait1Msec(1000);
        if (getColorName(colorSensor) == target_colour){
            objectSeen = 1;
            setMotorSpeed(baseMotor, 0); //stop
            break;
        }
    }
    wait1Msec(1000);
}

void doSweepSearch(){
    rotateBase(-700); //sweep right
    wait1Msec(3000);
    startResets();
    rotateBase(700000); //return to base
    wait1Msec(3000);
    rotateBase(3000000); //sweep left
    wait1Msec(3000);
    rotateBase(0); //return to base
}

//pass +ve speed for rotate right, -ve speed for rotate left
//returns to start position based on touch sensor
//void rotateBaseToStart(int speed){
//
//}

//pass +ve motorTarget to lift arm, -ve motorTarget to drop arm, 0 to reset to position
void liftArm(int motorTarget){
    setMotorTarget(armMotor, motorTarget, armMotorSpeed); //rotate to desired angle
    wait1Msec(3000);
}

//pass +ve motorTarget to clamp, -ve motorTarget to unclamp
void moveClamp(int motorTarget){
    setMotorTarget(clampMotor, motorTarget, clampMotorSpeed); //rotate to desired angle
    wait1Msec(3000);
}

void retrieveAndPlaceObject(){
    //lift object up from object position
    liftArm(-60); //rough estimate for now, drop arm down just above object
    moveClamp(50); //clamp object
    liftArm(60); //lift up object

    //put object down in start position
    rotateBase(0); //sweep back to base
    liftArm(-60); //move object down just at floor level
    moveClamp(-50); //unclamp from object
    liftArm(60); //lift up empty arm
}

task main()
{
    /* main steps:
     * 1: rotate right and left until clamp either sees an object or rotation hits 180/-180
     * 2: if object seen, rotate armMotor down
     * 4: run clampMotor to clamp object
     * 5: rotate armMotor up
     * 6: rotate base back to start position
     * 7: rotate armMotor down
     * 8: unclamp to drop object
     * 9: reset robot: lift arm up to base, start program again
     */

    startResets(); //initialises all motor encoders to 0
    while (objectSeen == 0){ //keep repeatedly sweeping until object found
        doSweepSearch();

        if (objectSeen == 1){
            retrieveAndPlaceObject();
            startResets();
            objectSeen = 0;
        }
    }

}

