#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     gyroArm,        sensorEV3_Gyro)
#pragma config(Sensor, S4,     gyroTilt,       sensorEV3_Gyro)
#pragma config(Motor,  motorA,          clampMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          armMotor,      tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          baseMotor,     tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void startResets();
void resetGyroArmAndTilt();
void armUpDown(int motorTarget);
void openCloseClamp(int option);
void startMotion();
void searchRight();
void turnLeft();
void retrieveObject();
void placeObject();


int baseMotorSpeed = 50;
int armMotorSpeed = 30;
int clampMotorSpeed = 30;


void startResets(){
    resetMotorEncoder(baseMotor);
    resetMotorEncoder(armMotor);
    resetMotorEncoder(clampMotor);
}

void resetGyroArmAndTilt()
{
    resetGyro(gyroArm);
    resetGyro(gyroTilt);
}

// +ve motor target for up, -ve motor target for down (since -motorTarget)
void armUpDown(int motorTarget)
{
    setMotorTarget(armMotor, -motorTarget, armMotorSpeed); //rotate to desired angle
    wait1Msec(3000);
}

//option 1 to open, option 2 to close
void openCloseClamp(int option)
{
    if (option == 1) //open
    {
        setMotorTarget(clampMotor, -100, clampMotorSpeed);
        wait1Msec(3000);
    }
    else //close
    {
        setMotorTarget(clampMotor, 70, clampMotorSpeed);
        wait1Msec(3000);
    }
}

void startMotion()
{
    startResets();
    armUpDown(200); //up
    startResets();
    openCloseClamp(2); //close
}

void searchRight()
{
    bool button_pressed = false;
    setMotorTarget(baseMotor, 20000, baseMotorSpeed);
    wait1Msec(3000);
    while (!button_pressed)
    {
        if (getTouchValue(touchSensor)>0)
        {
            button_pressed = true;
            resetGyro(gyroArm);
        }
    }
}

void turnLeft()
{
    bool objFound = false;
    setMotorSpeed(baseMotor, -30);
    while (!objFound && getGyroDegrees(gyroArm) > -80)
    {
        if (getColorReflected(colorSensor) > 1 )
        {
            objFound = true;
        }
    }
    wait1Msec(200);
    setMotorSpeed(baseMotor,0);
}

void retrieveObject()
{
    startResets();
    openCloseClamp(1); //open
    armUpDown(-70); //down
    openCloseClamp(2); //close
    startResets();
    armUpDown(150); //up
}

void placeObject()
{
    searchRight();
    armUpDown(-70); //down
    openCloseClamp(1); //open
    armUpDown(200); //up
}


task main()
{
    resetGyroArmAndTilt();
    startMotion();
    searchRight();
    turnLeft();
    retrieveObject();
    placeObject();
}